server:
  servlet:
    context-path: /clients
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.17:5432/bank
    username: postgres
    password: homeassistant
  jpa:
    show-sql: false
